### ISSUE TITLE
Min sdk version 23 ?

### ISSUE THREAD

**Issue by rravindranaik111** [NiklasMerz/fingerprint-aio-demo#2]
It gave me error Authentication invalid minimum sdk version 23 required.

How I can resolve this if I want less than that ?

Thanks in advance

**Comment by NiklasMerz** [comment]
When do you get this warning? While using authentication or in general?

API version 23 is requiered for using the Android built-in fingerprint authentication. Some deices support fingerprint authentioncation prior Android 6.0 but their sensor is enabled by device or manufacturer APIs, which are currently not supported by this plugin. Let me know if you need improvements of this plugin.

**Comment by rravindranaik111** [comment]
Hello, thanks for your quick reply. 

Did you mean that this will not work in android 5.0 ? because I want to implement this on android 5.0 mobile phone. How can execute this ?

In my config.xml file it look like this

<preference name="android-targetSdkVersion" value="23"/>
<preference name="android-minSdkVersion" value="16"/>

I have to change this to 

<preference name="android-targetSdkVersion" value="23"/>
<preference name="android-minSdkVersion" value="23"/>

IF yes please let me know ?

also I tried this on android 5.0 but it gives me "Parse error".

I am also attaching a error message screenshot
![screenshot_2017-01-22-09-21-22](https://cloud.githubusercontent.com/assets/25271489/22179837/9063ce54-e084-11e6-841b-dd923aa3acf5.png)
![screenshot_2017-01-22-09-21-30](https://cloud.githubusercontent.com/assets/25271489/22179838/90669152-e084-11e6-8945-4b6054ed8eb5.png)

**Comment by NiklasMerz** [comment]
At the moment you cannot implement fingerprint authentication with this plugin on Android 5.0. Unfortunately Android 5 does not support fingerprint authentication by default so you will have to find a workaround.

@rravindranaik111 I will let you know if this plugin supports Android 5

**Comment by NiklasMerz** [comment]
@rravindranaik111 Which device did you use for testing this?
