### ISSUE TITLE
How to add support for different languages like greek(el) and netherlands(NL)

### ISSUE THREAD

**Issue by shivalipawar** [NiklasMerz/fingerprint-aio-demo#4]
For both android and iOS.
Also , i  i want to use  maxAttempts  to 3, but maxAttempts does not seem to work.

**Comment by NiklasMerz** [comment]
For adding you could copy one of the values folder, rename it and add your translation:

https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/tree/master/res/android

I would appreciate a pull request with your translations.

Currently the number is fixed. You could open an issue on the plugin project and this could be changed. https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/new
