### ISSUE TITLE
Differents return on Android and iOS

### ISSUE THREAD

**Issue by juniorari** [NiklasMerz/fingerprint-aio-demo#5]
Hi Niklas, great plugin, but i have a issue testing your plugin on both platforms.
I noticed who the return of isAvailable() on Android is one string: 'OK'.
But the same method on iOS is another string: 'Available'.
And the result of authentication on both platforms is differents too.
On Android the result is a object with parameter withFingerprint, who returns a string hashed, but on iOS, the return of the method is a string: 'Success'.
Now you can fix it on next versions ;-)

**Comment by NiklasMerz** [comment]
This is a plugin issue. See https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/75
